### ISSUE TITLE
Class 'PhpOffice\PhpSpreadsheet\IOFactory' not found

### ISSUE THREAD

**Issue by ma-gu-16** [sudhaus7/typo3-xlsimport#1]
Class 'PhpOffice\PhpSpreadsheet\IOFactory' not found

in XlsimportController.php line 258

**Comment by foppelfb** [comment]
Sorry, we need more information than that...

Typo3 Version?  
PHP Version?
installed via composer or manual install?

Please check if the File vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/IOFactory.php exists.

**Comment by ma-gu-16** [comment]
Typo 10.4.2 Apache, PHP 7.4.5

installed via extension manager (typo3 backend).

greetings

**Comment by ma-gu-16** [comment]
> Sorry, we need more information than that...
> 
> Typo3 Version?
> PHP Version?
> installed via composer or manual install?
> 
> Please check if the File vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/IOFactory.php exists.

nope. ;-)

**Comment by foppelfb** [comment]
Ok, need to check with a manual install

**Comment by ma-gu-16** [comment]
composer doesnt work too. it creates this path: public/typo3/ instead of taking the root directory, if i install it via composer the whole t3core is broken. because it sets differenc class mapping to the wrong directory. greetings

**Comment by foppelfb** [comment]
using composer install inside the extension is basically only for development. You'd have to set up the whole typo3 in composer mode. I am testing right now, there will be a working extension for manual install available shortly

**Comment by foppelfb** [comment]
The Version 1.0.5 has been uploaded to the Extension Repository just now, please check if this works for you

**Comment by ma-gu-16** [comment]
works, thank you
