### ISSUE TITLE
Backend Error after EM Installation version 1.0.6 (TYPO3 7.6.49) - LanguageService does not exist

### ISSUE THREAD

**Issue by jochla** [sudhaus7/typo3-xlsimport#16]
I get this Message:

Could not analyse class: "TYPO3\CMS\Core\Localization\LanguageService" maybe not loaded or no autoloader? Class TYPO3\CMS\Core\Localization\LanguageService does not exist

Update german language package was done.

**Comment by foppelfb** [comment]
Hi, can you please confirm wether you use composer as installation method for the extension, or if you upload it as zip downloaded from extensions.typo3.org?

**Comment by jochla** [comment]
Installation method: I install the extension with the TYPO3 Extension Manager and select the last version (1.0.6) for TYPO3 7.6.

**Comment by foppelfb** [comment]
Please check out the now published 1.0.7 
I am not entierly sure if the correct version of the phpspreadsheet library has been added to the zip, so please let me know if there are further problems

**Comment by jochla** [comment]
The error no longer occurs. Thank you so much!

**Comment by calien666** [comment]
After all there is a Core problem with flux used and LanguageService. Please let us know, if you are using flux inside your installation.

**Comment by jochla** [comment]
No, I'm not using flux in my installation.

**Comment by calien666** [comment]
Problem seems to be solved. Will close this for now
