### ISSUE TITLE
Configurable upload folder

### ISSUE THREAD

**Issue by responseinformationsdesign** [sudhaus7/typo3-xlsimport#18]
Uploads should be saved to "uploads/tx_xlsimport" instead of site root because of default folder permissions and import file may contain sensitive personal data.

**Comment by foppelfb** [comment]
As an addendum: if the xls contains personal data, 'uploads/tx_xlsimport' is the worst place to store it, as this folder would be accessible via browser/web, the folder being located under the Document-root

**Comment by responseinformationsdesign** [comment]
You´re totally right. The safest solution would be to automatically delete the file direct after import.
