### ISSUE TITLE
Comparison with External Import

### ISSUE THREAD

**Issue by fsuter** [sudhaus7/typo3-xlsimport#21]
Hi there.

Earlier this year, I submitted my extension External Import in the documentation contest. The Documentation Team gave me the feedback that one improvement could be to explain to users how External Import differs from other import extensions, in order to help users make the best choice for them. One such extension is yours, "xlsimport".

I think that it is a good suggestion, but a bit embarrassing, because I don't know your extension. I have read the manual and tried to assess what the main differences are and to sum that up briefly in External Import's manual: https://docs.typo3.org/p/cobweb/external_import/main/en-us/Introduction/Index.html#alternatives

I have tried to find pros and cons, as this is really not about pretending that my extension is better than others. As such I would be glad if you could review what I said about "xlsimport" and tell me what you think about it. I'm fully open to suggestions and corrections. I realize that the reverse of my situation may also be true: you may not know much about External Import...

Thanks in advance for your contribution.

**Comment by foppelfb** [comment]
I am so sorry for not getting back sooner to you. The last 3 Months were pretty hectic for me here, so I could not pay as close attention to my notifications as I should have.

I think your paragraph about xlsimport sums it up pretty much. It is in fact designed for manual one-time imports via the backend. The Interface allows you to map each singular import in a different way, and it is exclusively targeted to data stored in a spreadsheet, nothing less, nothing more.

**Comment by fsuter** [comment]
Thanks a lot for your feedback. I slightly changed the wording for the next version, based on what you say.

I wish you a nice end of year, with more quiet time.
