### ISSUE TITLE
Undocumented configuration options

### ISSUE THREAD

**Issue by msollmann** [sudhaus7/typo3-xlsimport#22]
In 3.0.0 there are 2 hidden configuration options: uploadFolder and duplicationBehavior. One can use it like:

```
module.tx_xlsimport {
	settings {
		allowedTables = fe_users
		uploadFolder = /uploads/tx_xlsimport
		duplicationBehavior = ???
	}
}
```

But they are neither documented (https://docs.typo3.org/p/sudhaus7/xlsimport/3.0/en-us/Configuration/Index.html#configuration) nor to be found in example configuration ext_typoscript_setup.typoscript.

Would be great if the module would create the folder if not existing and would add a .htaccess with:
Order allow,deny
Deny from all

**Comment by Nestrot** [comment]
Look here

https://api.typo3.org/9.5/class_t_y_p_o3_1_1_c_m_s_1_1_core_1_1_resource_1_1_duplication_behavior.html

**Comment by calien666** [comment]
These hidden "features" are no longer present, as I removed Extbase and made the extension safe for future TYPO3 instances. In readme they where documented. I have to update documentation.
