### ISSUE TITLE
PHP Warning: Undefined array key 

### ISSUE THREAD

**Issue by heyse-dc** [sudhaus7/typo3-xlsimport#27]
Nice Extension but unfortunately it does not import.

Trying to import into fe_users via Excel or CSV file.
Setup as described:

module.tx_xlsimport {
    settings {
        allowedTables = fe_users
        # {storageUid}:{folderIdentifier} eg: 1:user_upload/data/import
        uploadFolder = 1:user_upload/tx_xlsimport
        # replace | rename | cancel
        duplicationBehavior = rename
    }
}

XLSIMPORT Vers. 4.0.0 via TER
PHP 8.0
TYPO3 11.5.18

Message after file upload:

(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception

PHP Warning: Undefined array key "SUDHAUS7\Xlsimport\Controller\XlsimportController" in /html/typo3/typo3conf/ext/xlsimport/Classes/Controller/XlsimportController.php line 404

**Comment by foppelfb** [comment]
Fixed in the latest TER and Packagist Release, duplicate of #25
