### ISSUE TITLE
Import of csv data to tt_address fails

### ISSUE THREAD

**Issue by zottelmann** [sudhaus7/typo3-xlsimport#28]
Hello!

I try to import a csv list to a folder. the list contains name, adress, website, longitude, latitude. A few weeks before it did work, but when i try now i just get this error(i blanked out sensible data with ***):

`GET https://nominatim.openstreetmap.org/search?country=DE&email=****=1&format=jsonv2&q=***name***+30` resulted in a `400 Bad Request` response: {"error":{"code":400,"message":"Structured query parameters(amenity, street, city, county, state, postalcode, country) c (truncated...) 
`
It looks like suddenly the data structure is not accepted anymore, but this worked before. What can i do?
I am using typo3 9.5.31 

Thanks

**Comment by foppelfb** [comment]
I am sorry I don't see the relevance to the xls-importer? We're not the hoster or admin for https://nominatim.openstreetmap.org/
please explain?

**Comment by zottelmann** [comment]
Well i was hoping you can point me to the right direction, sice the error occures when i try to import a csv-file using the plugin. if you are sure it has nothing to do with the plugin i will search elsewhere ;)

**Comment by foppelfb** [comment]
Additional Question: are there - in the CSV - actually values for address, city, zip, country and such? because the error-message from the openstreetmap service indicates that those are missing. In this case the error lies in that service, as it tries to look up incomplete data...

**Comment by foppelfb** [comment]
Another note, the error-message states that the problem is that structured data and free data (parameter country, parameter email AND the unstructured lookup q parameter)) are set, and it doesn't like that

**Comment by zottelmann** [comment]
Yes i am trying to import name, address  and longitude/latitude from a CSV into tt_address for usage with ods_osm. i actually use just these entrys. manually creating a tt_address record is no problem. i will try to fill in missing parameters, but i cannot see why it works manully (even without all needed params) and not if i import the data. thank you for your time :)

**Comment by zottelmann** [comment]
Stupid me. It actually was the missing data. Thank you very much!

**Comment by foppelfb** [comment]
You need to set a field type to structured. That helps
