### ISSUE TITLE
Use of the extension with users without admin rights not possible

### ISSUE THREAD

**Issue by ChristianRostock** [sudhaus7/typo3-xlsimport#32]
I would like to release the xlsimport extension for a backend user/group.
This user is not an administrator. The user has access to the XLS Importer module and can also access all data/tables to be imported.

I have set the release of the table via the settings and the import works for me as administrator without any problems.
However, if the user now wants to access the XLS Importer module, he sees the page tree released for him and otherwise receives a 503 error.

I also added this settings:

```
module.tx_xlsimport {
settings {
allowedTables = tx_psn_domain_model_publication
uploadFolder = 1:user_upload/xml_import
duplicationBehavior = rename
}
}
```

The user_upload/ folder is mounted for the user and therefore also the xml_import/ folder can be accessed it.

**Comment by ErHaWeb** [comment]
I have reproduced this case and can confirm the problem. Even if the non-admin user is assigned all necessary rights in the access module, the 503 error (with Message "You are not allowed to manipulate records on this page") is thrown in the backend when the xlsimport module is selected.

The following code section seems to be responsible:

`Classes/Controller/XlsimportController.php` line 75 - 86:

```php
$page = (int)GeneralUtility::_GET('id');
$minimalPage = [
    'uid' => $page,
];

DebugUtility::debug($minimalPage);
if (!AccessUtility::getBackendUser()->doesUserHaveAccess($minimalPage, Permission::PAGE_EDIT)) {
    throw new AccessDeniedException(
        'You are not allowed to manipulate records on this page',
        1676071343135
    );
}
```

As far as I can tell, it is not sufficient to pass just the `uid` in the row-array as first parameter for method `doesUserHaveAccess`. The fields `perms_userid`, `perms_user`, `perms_groupid`, `perms_group` and `perms_everybody` are missing, which are required later in `BackendUserAuthentication::calcPerms` to determine the authorization.
