### ISSUE TITLE
fetchAllNumeric() error in 10.4, fetchAll() works

### ISSUE THREAD

**Issue by zabinetta** [sudhaus7/typo3-xlsimport#5]
Hello,
today we used xlsimport in our typo3 10.4.20 installation. 
we could not import xls files, Error at upload:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to undefined method Doctrine\DBAL\Driver\Mysqli\MysqliStatement::fetchAllNumeric() | Error thrown in file /www/htdocs/xxxxxxx/html_104/typo3conf/ext/xlsimport/Classes/ViewHelpers/Backend/TcaNodeViewHelper.php in line 48. 
fetchAll() seems to work. maybe it's too early to migrate..
with the best regards,
Sabine

**Comment by zabinetta** [comment]
Dear Markus,
my installation is not composter based. PHP 7.4.19, MySQL 5.7.34.

**Comment by calien666** [comment]
Was resolved with the last version, so I will close
