### ISSUE TITLE
Error on TYPO3 8.7-installation

### ISSUE THREAD

**Issue by wini2** [sudhaus7/typo3-xlsimport#53]
I need to import csv to fe_user-table
My setup:
module.tx_xlsimport {
    settings {
        allowedTables := addToList(fe_users)
    }
}

I tried serveral xlss/csv-Variants, e.g.
10;user1@meinanbieter.de;1000
11;user2@meinanbieter.de;1001

Tyring to import I get an error
json_decode() expects parameter 1 to be string, array given 

I'm using 
TYPO3 8.7.18
xlsimport 1.0.7 (Version 1.1.0 shows up the error decripted in #16)

**Comment by calien666** [comment]
I'm sorry, but as we don't support this old version anymore, we cannot support on your issue.
As a security hint, you should not use this instance in a live system anymore, as your TYPO3 version is at least 6 years old and until ELTS release you missed 6 security fixes in your TYPO3 instance.
